projects:
  coolweb2:
    schemaPath: amplify/backend/api/coolweb2/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
      - src/graphql/custom-queries.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-west-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
